# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cAuthor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='cCreateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
