# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0003_functionsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionsmodel',
            name='functionTest',
            field=models.CharField(default='', max_length=500),
        ),
    ]
