# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0004_functionsmodel_functiontest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionsmodel',
            name='functionTest',
        ),
    ]
