# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0005_remove_functionsmodel_functiontest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionsmodel',
            name='fdocument',
        ),
        migrations.DeleteModel(
            name='functionsModel',
        ),
    ]
